---
- name: restart ctdb
  ansible.builtin.systemd:
    name: ctdb
    state: restarted

- name: restart samba
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - smbd
    - nmbd
  failed_when: false
